### ISSUE TITLE
Remove me from Travis configuration 

### ISSUE THREAD

**Issue by jamtur01** [lucraeskin/puppet-servicenowreporter#1]
Hi

You've obviously copied one of my repos including my TravisCI configuration. I am getting all your CI emails as a result. Please fix.

**Comment by EnoxCode** [comment]
Hi,

Yes i copied your Travis config. My apologies. I fixed it.

Again my apologies.

Kind regards,
Luc

Sent from my iPhone

On 10 Jan 2016, at 11:15, James Turnbull <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi

You've obviously copied one of my repos including my TravisCI configuration. I am getting all your CI emails as a result. Please fix.

##

**Comment by EnoxCode** [comment]
Hi,

Yes i copied your Travis config. My apologies. I fixed it.

Again my apologies.

Kind regards,
Luc
